import { Injectable, signal } from '@angular/core';

export type Language = 'en' | 'mr' | 'hi';

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home', services: 'Services', howItWorks: 'How It Works', about: 'About', contact: 'Contact', quote: 'Get Quote',
    footerDescription: 'Professional housekeeping and maintenance services for homes, offices, and industrial facilities.',
    quickLinks: 'Quick Links', contactInfo: 'Contact Info', housekeeping: 'Housekeeping', maintenance: 'Maintenance',
    industrialCleaning: 'Industrial Cleaning', officeMaintenance: 'Office Maintenance', allRights: 'All rights reserved.',
    servicesEyebrow: 'One call. All services.', servicesTitle: 'Professional care for every kind of space.',
    servicesDescription: 'Perfect Multi Services brings housekeeping, cleaning, maintenance, and pest control together under one dependable partner.',
    requestQuote: 'Request a tailored quote', capabilities: 'Our capabilities', capabilitiesTitle: 'Solutions designed around your property.',
    capabilitiesText: 'Whether you need a one-time deep clean or an ongoing facility support plan, our team can shape the service around your priorities, schedule, and budget.',
    residential: 'Residential Housekeeping', commercial: 'Commercial Cleaning', maintenanceSupport: 'Maintenance Support', pestControl: 'Pest Control',
    planService: 'Plan this service', specific: 'Need something specific?', tellUs: 'Tell us what your space needs.', talkTeam: 'Talk to our team',
    processEyebrow: 'How it works', processTitle: 'A simpler way to keep your space at its best.',
    processDescription: 'From the first conversation to the final follow-up, our process is designed to be clear, convenient, and dependable.',
    approach: 'Our approach', fourSteps: 'Four steps. One trusted partner.', servicePromise: 'Our service promise',
    startConversation: 'Start with a conversation', aboutEyebrow: 'One company. Multiple solutions.',
    aboutDescription: 'Reliable housekeeping, cleaning, maintenance, and pest control support for homes, offices, and facilities.',
    contactTitle: 'Contact Us', contactDescription: 'Tell us about your home, office, or facility and we will recommend the right service plan.',
    whatNext: 'What happens next?', sendMessage: 'Send Message', location: 'Location', email: 'Email', phone: 'Phone',
    selectLanguage: 'Language', loading: 'Loading services...', retry: 'Retry', bookService: 'Book a Service',
    whyChooseUs: 'Why Choose Us', customerRating: 'Customer Rating', homesServed: 'Homes Served', support: 'Support',
    popular: 'Popular', deepCleaning: 'Deep cleaning', sanitization: 'Sanitization', flexibleTiming: 'Flexible timing',
    sameDay: 'Same-day slot', trustedFamilies: 'Trusted by 1250+ families', difference: 'The Perfect difference',
    servicePrecision: 'Thoughtful service, delivered with precision.', ourServices: 'Our Services',
    professionalCare: 'Professional care for every space', learnMore: 'Learn More', chooseUs: 'Why choose us',
    cleanSpaces: 'Clean spaces. Trusted teams. Reliable service.', howSimple: 'Simple steps to a better space',
    fullName: 'Full Name', emailAddress: 'Email Address', phoneNumber: 'Phone Number', message: 'Message',
    selectService: 'Select a service', sendAnother: 'Send another message', thankYou: 'Thank you for your inquiry!',
    willContact: 'We will contact you soon.', otherWays: 'Other Ways to Reach Us',
    promoEyebrow: 'One call. All services.',
    promoHeading: 'Freedom from the daily cleaning hassle!',
    promoIntro: 'Reliable, professional and affordable care for homes, offices, hospitals, hotels and industries in Sangli.',
    promoDailyTag: 'Daily housekeeping',
    promoDailyTitle: 'Everyday cleanliness, everyday freshness.',
    promoDailyText: 'Trusted housekeeping for homes, offices, hospitals, hotels and industries.',
    promoDailyPoints: 'Homes|Offices|Hospitals|Hotels|Industries',
    promoKitchenTag: 'Kitchen & home cleaning',
    promoKitchenTitle: 'Morning mess already stressing you out?',
    promoKitchenText: 'Piled-up dishes, greasy counters and a messy floor. Our trained team takes the daily cleaning hassle off your hands.',
    promoKitchenPoints: 'Kitchen cleaning|Utensils & counters|Floor care',
    promoHomeTag: 'Regular home care',
    promoHomeTitle: '“Who will clean today?” is no longer your worry.',
    promoHomeText: 'Daily cleaning made simple, regular and professional, so every morning starts fresh.',
    promoHomePoints: 'Simple|Regular|Professional',
    promoSolarTag: 'Solar panel cleaning',
    promoSolarTitle: 'Clean panels, brighter tomorrow.',
    promoSolarText: 'We remove dust, dirt, bird droppings and stains to increase energy output and extend panel life.',
    promoSolarPoints: 'Improves efficiency|Extends panel life|Safe & damage-free|Lower electricity bills',
    promoSofaTag: 'Sofa & carpet cleaning',
    promoSofaTitle: 'Deep clean. Fresh feel. Healthy home.',
    promoSofaText: 'Professional sofa and carpet cleaning that removes dirt, stains, allergens and odours.',
    promoSofaPoints: 'Deep cleaning|Stain removal|Germ & allergen free|Quick dry',
    bookSlot: 'Book your cleaning slot',
    previousSlide: 'Previous slide',
    nextSlide: 'Next slide',
    specialEyebrow: 'Specialised care',
    specialHeading: 'Beyond everyday cleaning.',
    solarTagline: 'Maximise performance, save energy',
    solarTitle: 'Solar Panel Cleaning',
    solarText: 'Clean panels, better efficiency. Our professional cleaning keeps your solar system producing more power for longer.',
    solarEfficiency: 'Improves efficiency',
    solarEfficiencyText: 'Clean panels absorb more sunlight and generate more power.',
    solarLife: 'Extends panel life',
    solarLifeText: 'Regular cleaning prevents dirt buildup and damage.',
    solarSafe: 'Safe & damage-free',
    solarSafeText: 'Advanced tools and eco-friendly cleaning methods.',
    solarCost: 'Cost effective',
    solarCostText: 'Better efficiency means lower electricity bills.',
    solarSites: 'Residential & commercial',
    solarSitesText: 'Homes, offices, industries and large solar plants.',
    sofaTagline: 'Deep clean. Fresh feel. Healthy home.',
    sofaTitle: 'Sofa & Carpet Cleaning',
    sofaText: 'Enjoy a cleaner, fresher and healthier living and working space, free of dirt, stains, allergens and odours.',
    sofaDeep: 'Deep cleaning',
    sofaDeepText: 'Removes deep-down dirt and dust.',
    sofaStain: 'Stain removal',
    sofaStainText: 'Effectively removes tough stains.',
    sofaGerm: 'Germ & allergen free',
    sofaGermText: 'Kills bacteria and allergens.',
    sofaOdour: 'Odour elimination',
    sofaOdourText: 'Leaves your sofa and carpet fresh.',
    sofaDry: 'Quick dry',
    sofaDryText: 'Low-moisture cleaning for a quick drying time.',
    assureTrained: 'Trained & verified professionals',
    assureEquipment: 'Advanced cleaning equipment',
    assureSafe: 'Safe & eco-friendly chemicals',
    assureSatisfaction: 'Satisfaction guaranteed',
    assureCommercial: 'Residential & commercial services',
    callToday: 'Call us today',
    bookSlotNow: 'Book your cleaning slot now',
    oneCallTagline: 'One call, all services. Reliable | Professional | Affordable',
    officeAddress: 'Flat no. 1, Nitiraj Apartment, near Rajmati Girls High School, Neminathnagar, Vishrambag, Sangli 416415'
  },
  mr: {
    home: 'मुख्यपृष्ठ', services: 'सेवा', howItWorks: 'सेवा कशी मिळते', about: 'आमच्याबद्दल', contact: 'संपर्क', quote: 'कोट मिळवा',
    footerDescription: 'घरे, कार्यालये आणि औद्योगिक सुविधांसाठी व्यावसायिक हाऊसकीपिंग व देखभाल सेवा.',
    quickLinks: 'जलद दुवे', contactInfo: 'संपर्क माहिती', housekeeping: 'हाऊसकीपिंग', maintenance: 'देखभाल',
    industrialCleaning: 'औद्योगिक स्वच्छता', officeMaintenance: 'कार्यालय देखभाल', allRights: 'सर्व हक्क राखीव.',
    servicesEyebrow: 'एक कॉल. सर्व सेवा.', servicesTitle: 'प्रत्येक जागेसाठी व्यावसायिक सेवा.',
    servicesDescription: 'हाऊसकीपिंग, स्वच्छता, देखभाल आणि पेस्ट कंट्रोल एका विश्वासू भागीदाराकडून.',
    requestQuote: 'तुमचा कोट मागवा', capabilities: 'आमच्या सेवा', capabilitiesTitle: 'तुमच्या जागेसाठी योग्य उपाय.',
    capabilitiesText: 'एकदाच डीप क्लीनिंग असो किंवा नियमित सुविधा सेवा, तुमच्या गरजेनुसार आम्ही योजना तयार करतो.',
    residential: 'घरगुती हाऊसकीपिंग', commercial: 'व्यावसायिक स्वच्छता', maintenanceSupport: 'देखभाल सेवा', pestControl: 'पेस्ट कंट्रोल',
    planService: 'ही सेवा निवडा', specific: 'तुमची गरज वेगळी आहे?', tellUs: 'तुमच्या जागेबद्दल आम्हाला सांगा.', talkTeam: 'आमच्या टीमशी बोला',
    processEyebrow: 'सेवा कशी मिळते', processTitle: 'तुमची जागा उत्तम ठेवण्याचा सोपा मार्ग.',
    processDescription: 'पहिल्या संवादापासून अंतिम फॉलो-अपपर्यंत आमची प्रक्रिया स्पष्ट आणि विश्वासार्ह आहे.',
    approach: 'आमचा दृष्टिकोन', fourSteps: 'चार पायऱ्या. एक विश्वासू भागीदार.', servicePromise: 'आमचे सेवा वचन',
    startConversation: 'संवाद सुरू करा', aboutEyebrow: 'एक कंपनी. अनेक उपाय.',
    aboutDescription: 'घरे, कार्यालये आणि सुविधांसाठी विश्वासार्ह हाऊसकीपिंग, स्वच्छता, देखभाल व पेस्ट कंट्रोल.',
    contactTitle: 'संपर्क करा', contactDescription: 'तुमच्या जागेबद्दल सांगा आणि आम्ही योग्य सेवा योजना सुचवू.',
    whatNext: 'पुढे काय?', sendMessage: 'संदेश पाठवा', location: 'ठिकाण', email: 'ईमेल', phone: 'फोन',
    selectLanguage: 'भाषा', loading: 'सेवा लोड होत आहेत...', retry: 'पुन्हा प्रयत्न करा', bookService: 'सेवा बुक करा',
    whyChooseUs: 'आम्हाला का निवडावे', customerRating: 'ग्राहक रेटिंग', homesServed: 'सेवा दिलेली घरे', support: 'मदत',
    popular: 'लोकप्रिय', deepCleaning: 'डीप क्लीनिंग', sanitization: 'निर्जंतुकीकरण', flexibleTiming: 'सोयीची वेळ',
    sameDay: 'त्याच दिवशीची वेळ', trustedFamilies: '१२५०+ कुटुंबांचा विश्वास', difference: 'Perfect मधील फरक',
    servicePrecision: 'नियोजनबद्ध आणि अचूक सेवा.', ourServices: 'आमच्या सेवा', professionalCare: 'प्रत्येक जागेसाठी व्यावसायिक सेवा',
    learnMore: 'अधिक जाणून घ्या', chooseUs: 'आम्हाला का निवडावे', cleanSpaces: 'स्वच्छ जागा. विश्वासू टीम. उत्तम सेवा.',
    howSimple: 'उत्तम जागेसाठी सोप्या पायऱ्या', fullName: 'पूर्ण नाव', emailAddress: 'ईमेल पत्ता', phoneNumber: 'फोन नंबर',
    message: 'संदेश', selectService: 'सेवा निवडा', sendAnother: 'दुसरा संदेश पाठवा', thankYou: 'आपल्या चौकशीबद्दल धन्यवाद!',
    willContact: 'आम्ही लवकरच संपर्क करू.', otherWays: 'आमच्याशी संपर्क करण्याचे इतर मार्ग',
    promoEyebrow: 'एक कॉल. सर्व सेवा.',
    promoHeading: 'दररोजच्या स्वच्छतेच्या कटकटीपासून सुटका!',
    promoIntro: 'सांगलीतील घर, कार्यालय, हॉस्पिटल, हॉटेल आणि उद्योगांसाठी विश्वासार्ह, प्रोफेशनल आणि परवडणारी सेवा.',
    promoDailyTag: 'दैनंदिन हाऊसकीपिंग',
    promoDailyTitle: 'रोजची स्वच्छता, रोजची ताजगी',
    promoDailyText: 'घर, कार्यालय, हॉस्पिटल, हॉटेल आणि उद्योगांसाठी विश्वासार्ह हाऊसकीपिंग सेवा.',
    promoDailyPoints: 'घर|कार्यालय|हॉस्पिटल|हॉटेल|उद्योग',
    promoKitchenTag: 'किचन व घर स्वच्छता',
    promoKitchenTitle: 'सकाळ होताच स्वच्छतेचं टेन्शन सुरू?',
    promoKitchenText: 'भांड्यांचा ढीग, तेलकट ओटा आणि पसारा — आमची प्रशिक्षित टीम दररोजच्या स्वच्छतेची कटकट दूर करते.',
    promoKitchenPoints: 'किचन स्वच्छता|भांडी व ओटा|फरशी स्वच्छता',
    promoHomeTag: 'नियमित घर स्वच्छता',
    promoHomeTitle: 'सकाळचा पहिला विचार — आज साफसफाई कोण करणार?',
    promoHomeText: 'रोजची स्वच्छता सोपी, नियमित आणि प्रोफेशनल — त्यामुळे प्रत्येक सकाळ ताजीतवानी.',
    promoHomePoints: 'सोपी|नियमित|प्रोफेशनल',
    promoSolarTag: 'सोलर पॅनल स्वच्छता',
    promoSolarTitle: 'स्वच्छ पॅनल, उज्ज्वल उद्या.',
    promoSolarText: 'धूळ, माती, पक्ष्यांची विष्ठा आणि डाग काढून ऊर्जा उत्पादन व पॅनलचे आयुष्य वाढवतो.',
    promoSolarPoints: 'कार्यक्षमता वाढते|पॅनलचे आयुष्य वाढते|सुरक्षित व नुकसानरहित|वीज बिल कमी',
    promoSofaTag: 'सोफा व कार्पेट स्वच्छता',
    promoSofaTitle: 'सखोल स्वच्छता. ताजेपणा. निरोगी घर.',
    promoSofaText: 'सोफा आणि कार्पेटवरील धूळ, डाग, ॲलर्जन्स आणि दुर्गंधी दूर करणारी व्यावसायिक स्वच्छता.',
    promoSofaPoints: 'डीप क्लीनिंग|डाग काढणे|जंतू व ॲलर्जन मुक्त|लवकर कोरडे',
    bookSlot: 'स्वच्छता स्लॉट बुक करा',
    previousSlide: 'मागील स्लाइड',
    nextSlide: 'पुढील स्लाइड',
    specialEyebrow: 'विशेष सेवा',
    specialHeading: 'रोजच्या स्वच्छतेपलीकडे.',
    solarTagline: 'जास्त कार्यक्षमता, ऊर्जेची बचत',
    solarTitle: 'सोलर पॅनल स्वच्छता',
    solarText: 'स्वच्छ पॅनल, जास्त कार्यक्षमता. आमच्या प्रोफेशनल स्वच्छतेमुळे तुमची सोलर यंत्रणा दीर्घकाळ जास्त वीज निर्माण करते.',
    solarEfficiency: 'कार्यक्षमता वाढते',
    solarEfficiencyText: 'स्वच्छ पॅनल जास्त सूर्यप्रकाश शोषून जास्त वीज निर्माण करतात.',
    solarLife: 'पॅनलचे आयुष्य वाढते',
    solarLifeText: 'नियमित स्वच्छतेमुळे धूळ साचणे व नुकसान टळते.',
    solarSafe: 'सुरक्षित व नुकसानरहित',
    solarSafeText: 'आधुनिक साधने आणि पर्यावरणपूरक पद्धती.',
    solarCost: 'किफायतशीर',
    solarCostText: 'जास्त कार्यक्षमता म्हणजे कमी वीज बिल.',
    solarSites: 'घरगुती व व्यावसायिक',
    solarSitesText: 'घरे, कार्यालये, उद्योग आणि मोठे सोलर प्लांट.',
    sofaTagline: 'सखोल स्वच्छता. ताजेपणा. निरोगी घर.',
    sofaTitle: 'सोफा व कार्पेट स्वच्छता',
    sofaText: 'धूळ, डाग, ॲलर्जन्स आणि दुर्गंधीमुक्त — अधिक स्वच्छ, ताजी आणि निरोगी राहण्याची व कामाची जागा.',
    sofaDeep: 'डीप क्लीनिंग',
    sofaDeepText: 'आतपर्यंत साचलेली धूळ व माती काढते.',
    sofaStain: 'डाग काढणे',
    sofaStainText: 'हट्टी डाग प्रभावीपणे काढते.',
    sofaGerm: 'जंतू व ॲलर्जन मुक्त',
    sofaGermText: 'जीवाणू आणि ॲलर्जन्स नष्ट करते.',
    sofaOdour: 'दुर्गंधी दूर',
    sofaOdourText: 'सोफा व कार्पेट ताजेतवाने ठेवते.',
    sofaDry: 'लवकर कोरडे',
    sofaDryText: 'कमी ओलाव्याची स्वच्छता, त्यामुळे लवकर कोरडे.',
    assureTrained: 'प्रशिक्षित व पडताळणी केलेले कर्मचारी',
    assureEquipment: 'आधुनिक स्वच्छता साधने',
    assureSafe: 'सुरक्षित व पर्यावरणपूरक रसायने',
    assureSatisfaction: 'समाधानाची हमी',
    assureCommercial: 'घरगुती व व्यावसायिक सेवा',
    callToday: 'आजच कॉल करा',
    bookSlotNow: 'आजच तुमचा स्वच्छता स्लॉट बुक करा',
    oneCallTagline: 'एक कॉल, सर्व सेवा. विश्वासार्ह | प्रोफेशनल | परवडणारी',
    officeAddress: 'फ्लॅट नं. १, नितीराज अपार्टमेंट, राजमती गर्ल्स हायस्कूलजवळ, नेमिनाथनगर, विश्रामबाग, सांगली ४१६४१५'
  },
  hi: {
    home: 'होम', services: 'सेवाएं', howItWorks: 'सेवा कैसे मिलती है', about: 'हमारे बारे में', contact: 'संपर्क', quote: 'कोट पाएं',
    footerDescription: 'घरों, कार्यालयों और औद्योगिक सुविधाओं के लिए पेशेवर हाउसकीपिंग और रखरखाव सेवाएं.',
    quickLinks: 'त्वरित लिंक', contactInfo: 'संपर्क जानकारी', housekeeping: 'हाउसकीपिंग', maintenance: 'रखरखाव',
    industrialCleaning: 'औद्योगिक सफाई', officeMaintenance: 'ऑफिस रखरखाव', allRights: 'सर्वाधिकार सुरक्षित.',
    servicesEyebrow: 'एक कॉल. सभी सेवाएं.', servicesTitle: 'हर जगह के लिए पेशेवर देखभाल.',
    servicesDescription: 'हाउसकीपिंग, सफाई, रखरखाव और पेस्ट कंट्रोल एक भरोसेमंद पार्टनर से.',
    requestQuote: 'कोट का अनुरोध करें', capabilities: 'हमारी सेवाएं', capabilitiesTitle: 'आपकी जगह के लिए सही समाधान.',
    capabilitiesText: 'एक बार की डीप क्लीनिंग हो या नियमित सुविधा सेवा, हम आपकी जरूरत के अनुसार योजना बनाते हैं.',
    residential: 'घरेलू हाउसकीपिंग', commercial: 'व्यावसायिक सफाई', maintenanceSupport: 'रखरखाव सहायता', pestControl: 'पेस्ट कंट्रोल',
    planService: 'यह सेवा चुनें', specific: 'कुछ खास चाहिए?', tellUs: 'अपनी जगह की जरूरत बताएं.', talkTeam: 'हमारी टीम से बात करें',
    processEyebrow: 'सेवा कैसे मिलती है', processTitle: 'अपनी जगह को बेहतर रखने का आसान तरीका.',
    processDescription: 'पहली बातचीत से अंतिम फॉलो-अप तक हमारी प्रक्रिया स्पष्ट और भरोसेमंद है.',
    approach: 'हमारा तरीका', fourSteps: 'चार कदम. एक भरोसेमंद पार्टनर.', servicePromise: 'हमारा सेवा वादा',
    startConversation: 'बातचीत शुरू करें', aboutEyebrow: 'एक कंपनी. अनेक समाधान.',
    aboutDescription: 'घरों, कार्यालयों और सुविधाओं के लिए भरोसेमंद हाउसकीपिंग, सफाई, रखरखाव और पेस्ट कंट्रोल.',
    contactTitle: 'संपर्क करें', contactDescription: 'अपनी जगह के बारे में बताएं और हम सही सेवा योजना सुझाएंगे.',
    whatNext: 'अब आगे क्या?', sendMessage: 'संदेश भेजें', location: 'स्थान', email: 'ईमेल', phone: 'फोन',
    selectLanguage: 'भाषा', loading: 'सेवाएं लोड हो रही हैं...', retry: 'फिर कोशिश करें', bookService: 'सेवा बुक करें',
    whyChooseUs: 'हमें क्यों चुनें', customerRating: 'ग्राहक रेटिंग', homesServed: 'सेवा प्राप्त घर', support: 'सहायता',
    popular: 'लोकप्रिय', deepCleaning: 'डीप क्लीनिंग', sanitization: 'सैनिटाइजेशन', flexibleTiming: 'लचीला समय',
    sameDay: 'उसी दिन का स्लॉट', trustedFamilies: '१२५०+ परिवारों का भरोसा', difference: 'Perfect का अंतर',
    servicePrecision: 'सोची-समझी और सटीक सेवा.', ourServices: 'हमारी सेवाएं', professionalCare: 'हर जगह के लिए पेशेवर देखभाल',
    learnMore: 'और जानें', chooseUs: 'हमें क्यों चुनें', cleanSpaces: 'स्वच्छ जगह. भरोसेमंद टीम. विश्वसनीय सेवा.',
    howSimple: 'बेहतर जगह के लिए आसान कदम', fullName: 'पूरा नाम', emailAddress: 'ईमेल पता', phoneNumber: 'फोन नंबर',
    message: 'संदेश', selectService: 'सेवा चुनें', sendAnother: 'दूसरा संदेश भेजें', thankYou: 'आपकी पूछताछ के लिए धन्यवाद!',
    willContact: 'हम जल्द ही आपसे संपर्क करेंगे.', otherWays: 'हमसे संपर्क करने के अन्य तरीके',
    promoEyebrow: 'एक कॉल. सभी सेवाएं.',
    promoHeading: 'रोज़ की सफाई की झंझट से छुटकारा!',
    promoIntro: 'सांगली में घर, ऑफिस, अस्पताल, होटल और उद्योगों के लिए भरोसेमंद, प्रोफेशनल और किफायती सेवा.',
    promoDailyTag: 'दैनिक हाउसकीपिंग',
    promoDailyTitle: 'रोज़ की सफाई, रोज़ की ताज़गी',
    promoDailyText: 'घर, ऑफिस, अस्पताल, होटल और उद्योगों के लिए भरोसेमंद हाउसकीपिंग सेवा.',
    promoDailyPoints: 'घर|ऑफिस|अस्पताल|होटल|उद्योग',
    promoKitchenTag: 'किचन और घर की सफाई',
    promoKitchenTitle: 'सुबह होते ही सफाई की टेंशन?',
    promoKitchenText: 'बर्तनों का ढेर, चिकना काउंटर और बिखरा सामान — हमारी प्रशिक्षित टीम रोज़ की सफाई की झंझट दूर करती है.',
    promoKitchenPoints: 'किचन की सफाई|बर्तन और काउंटर|फर्श की सफाई',
    promoHomeTag: 'नियमित घरेलू सफाई',
    promoHomeTitle: 'सुबह का पहला सवाल — आज सफाई कौन करेगा?',
    promoHomeText: 'रोज़ की सफाई आसान, नियमित और प्रोफेशनल — ताकि हर सुबह ताज़गी से शुरू हो.',
    promoHomePoints: 'आसान|नियमित|प्रोफेशनल',
    promoSolarTag: 'सोलर पैनल सफाई',
    promoSolarTitle: 'साफ पैनल, उज्ज्वल कल.',
    promoSolarText: 'धूल, मिट्टी, पक्षियों की बीट और दाग हटाकर ऊर्जा उत्पादन और पैनल की उम्र बढ़ाते हैं.',
    promoSolarPoints: 'बेहतर दक्षता|पैनल की लंबी उम्र|सुरक्षित और नुकसान-रहित|कम बिजली बिल',
    promoSofaTag: 'सोफा और कार्पेट सफाई',
    promoSofaTitle: 'गहरी सफाई. ताज़ा एहसास. स्वस्थ घर.',
    promoSofaText: 'सोफा और कार्पेट से धूल, दाग, एलर्जन और बदबू हटाने वाली पेशेवर सफाई.',
    promoSofaPoints: 'डीप क्लीनिंग|दाग हटाना|कीटाणु और एलर्जन मुक्त|जल्दी सूखना',
    bookSlot: 'सफाई स्लॉट बुक करें',
    previousSlide: 'पिछली स्लाइड',
    nextSlide: 'अगली स्लाइड',
    specialEyebrow: 'विशेष सेवाएं',
    specialHeading: 'रोज़ की सफाई से आगे.',
    solarTagline: 'ज़्यादा दक्षता, ऊर्जा की बचत',
    solarTitle: 'सोलर पैनल सफाई',
    solarText: 'साफ पैनल, बेहतर दक्षता. हमारी प्रोफेशनल सफाई से आपका सोलर सिस्टम लंबे समय तक ज़्यादा बिजली बनाता है.',
    solarEfficiency: 'बेहतर दक्षता',
    solarEfficiencyText: 'साफ पैनल ज़्यादा धूप सोखकर ज़्यादा बिजली बनाते हैं.',
    solarLife: 'पैनल की लंबी उम्र',
    solarLifeText: 'नियमित सफाई से धूल जमना और नुकसान रुकता है.',
    solarSafe: 'सुरक्षित और नुकसान-रहित',
    solarSafeText: 'आधुनिक उपकरण और पर्यावरण-अनुकूल तरीके.',
    solarCost: 'किफायती',
    solarCostText: 'बेहतर दक्षता यानी कम बिजली बिल.',
    solarSites: 'घरेलू और व्यावसायिक',
    solarSitesText: 'घर, ऑफिस, उद्योग और बड़े सोलर प्लांट.',
    sofaTagline: 'गहरी सफाई. ताज़ा एहसास. स्वस्थ घर.',
    sofaTitle: 'सोफा और कार्पेट सफाई',
    sofaText: 'धूल, दाग, एलर्जन और बदबू से मुक्त — ज़्यादा साफ, ताज़ा और स्वस्थ रहने व काम करने की जगह.',
    sofaDeep: 'डीप क्लीनिंग',
    sofaDeepText: 'अंदर तक जमी धूल और मिट्टी हटाती है.',
    sofaStain: 'दाग हटाना',
    sofaStainText: 'ज़िद्दी दाग असरदार तरीके से हटाती है.',
    sofaGerm: 'कीटाणु और एलर्जन मुक्त',
    sofaGermText: 'बैक्टीरिया और एलर्जन खत्म करती है.',
    sofaOdour: 'बदबू दूर',
    sofaOdourText: 'सोफा और कार्पेट को ताज़ा रखती है.',
    sofaDry: 'जल्दी सूखना',
    sofaDryText: 'कम नमी वाली सफाई, जिससे जल्दी सूखता है.',
    assureTrained: 'प्रशिक्षित और सत्यापित कर्मचारी',
    assureEquipment: 'आधुनिक सफाई उपकरण',
    assureSafe: 'सुरक्षित और पर्यावरण-अनुकूल केमिकल',
    assureSatisfaction: 'संतुष्टि की गारंटी',
    assureCommercial: 'घरेलू और व्यावसायिक सेवाएं',
    callToday: 'आज ही कॉल करें',
    bookSlotNow: 'आज ही अपना सफाई स्लॉट बुक करें',
    oneCallTagline: 'एक कॉल, सभी सेवाएं. भरोसेमंद | प्रोफेशनल | किफायती',
    officeAddress: 'फ्लैट नं. 1, नितीराज अपार्टमेंट, राजमती गर्ल्स हाईस्कूल के पास, नेमिनाथनगर, विश्रामबाग, सांगली 416415'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly language = signal<Language>((localStorage.getItem('pms-language') as Language) || 'en');

  constructor() {
    this.applyDocumentLanguage(this.language());
  }

  setLanguage(language: Language): void {
    this.language.set(language);
    localStorage.setItem('pms-language', language);
    this.applyDocumentLanguage(language);
  }

  private applyDocumentLanguage(language: Language): void {
    document.documentElement.lang = language === 'mr' ? 'mr-IN' : language === 'hi' ? 'hi-IN' : 'en';
  }

  t(key: string): string {
    return translations[this.language()][key] || translations.en[key] || key;
  }
}
